---
deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home/erkanerd/akaydintarim.com.tr/

    # Copy built files to web directory
    - /bin/cp -R dist/* $DEPLOYPATH

    # Copy server files (backend)
    - /bin/cp -R server $DEPLOYPATH/
    - /bin/cp package.json $DEPLOYPATH/

    # Copy database setup
    - /bin/cp -R database $DEPLOYPATH/

    # Set proper permissions
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
