---
deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home/erkanerd/akaydintarim.com.tr/

    # Install Node.js dependencies
    - npm install --production

    # Build the Vite project
    - npm run build

    # Copy built files to deployment path
    - /bin/cp -R dist/* $DEPLOYPATH

    # Copy server files and necessary files
    - /bin/cp -R server $DEPLOYPATH/
    - /bin/cp package.json $DEPLOYPATH/
    - /bin/cp .env $DEPLOYPATH/

    # Install production dependencies in deployment path
    - cd $DEPLOYPATH && npm install --production

    # Set proper permissions
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
