---
deployment:
  tasks:
    # Copy all files to public_html
    - export DEPLOYPATH=/home/username/public_html/
    - /bin/cp -R . $DEPLOYPATH

    # Install Node.js dependencies (if needed)
    - cd $DEPLOYPATH && npm install --production

    # Build the project
    - cd $DEPLOYPATH && npm run build

    # Copy built files to the correct location
    - cd $DEPLOYPATH && cp -R dist/* ./

    # Set proper permissions
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
