---
deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home/erkanerd/akaydintarim.com.tr/

    # Install Node.js dependencies
    - npm install

    # Build the Vite project
    - npm run build

    # Copy built files to public_html
    - /bin/cp -R dist/* $DEPLOYPATH

    # Copy server files (if needed)
    - /bin/cp -R server $DEPLOYPATH/
    - /bin/cp package.json $DEPLOYPATH/

    # Set proper permissions
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
